name = "Lucky"
uuid = "94236f11-8a78-480b-adc6-824e7df3001c"
authors = ["Olivier Milla <olivier.milla@hey.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
